[package]
name = "datex-web"
version = "0.0.16"
authors = [
    "Benedikt Strehle <benedikt@unyt.org>",
    "Jonas Strehle <jonas@unyt.org>",
]
license = "../LICENSE"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "s"
strip = true
lto = true
codegen-units = 1
panic = "abort"


[dependencies]
log = { version = "0.4", features = ["std", "serde"] }
# git = "https://github.com/unyt-org/datex"
datex-core = { version = "0.0.13", default-features = false, features = [
    "target_wasm",
    "compiler",
    "decompiler",
    "syntax_highlighting_legacy",
    "lsp_wasm",
    "disassembler",
] }
# git = "https://github.com/unyt-org/datex", branch = "release/0.0.11", 
datex-crypto-facade = { version = "0.0.3" }

async-trait = "0.1.87"
url = { version = "2.5.7" }
wasm-bindgen = { version = "=0.2.123", features = [] }
# FIXME make serde-wasm-bindgen optional
serde-wasm-bindgen = "0.6"
serde = { version = "1.0", features = ["derive"] }
# serde-wasm-bindgen = "0.6"

wasm-bindgen-futures = "0.4.61"
js-sys = "=0.3.100"


# webrtc
futures = { version = "0.3", default-features = false }                         # = "0.11", 
futures-timer = { version = "3", features = ["wasm-bindgen"] }
uuid = { version = "1.15.1", features = ["js"], optional = true }
futures-channel = "0.3.31"
specta-typescript = "0.0.9"
specta = "1.0.5"
gloo-timers = "0.3.0"
cfg-if = "1.0.1"
console_error_panic_hook = "0.1.7"
wasm-logger = "0.2.0"
strum = { version = "0.27.1", default-features = false, features = ["derive"] }


# swc
swc_common = "23"
swc_ecma_ast = "25"
swc_ecma_codegen = "28"
num-bigint = { version = "0.4", default-features = false }
dedent = "0.1.1"
indexmap = "2.14.2"

# webrtc
# tokio = { version = "1.43.0", default-features = false, features = [] }
[dependencies.web-sys]
version = "0.3.100"
features = [
    "Window",
    "AesCtrParams",
    "BinaryType",
    "Blob",
    "ErrorEvent",
    "FileReader",
    "MessageEvent",
    "ProgressEvent",
    "WebSocket",
    "Crypto",
    "SubtleCrypto",
    "CryptoKey",
    "CryptoKeyPair",
    "Serial",
    "SerialOptions",
    "SerialPort",
    "Navigator",
    "ReadableStream",
    "WritableStream",
    "SerialOptions",
    "ReadableStreamDefaultReader",
    "ReadableStreamReadResult",
    "WritableStreamDefaultWriter",
    "EventTarget",
    "MessageEvent",
    "RtcPeerConnection",
    "RtcSignalingState",
    "RtcSdpType",
    "RtcIceCandidateInit",
    "RtcIceConnectionState",
    "RtcSessionDescriptionInit",
    "RtcPeerConnectionIceEvent",
    "RtcIceCandidate",
    "RtcDataChannel",
    "RtcDataChannelEvent",
    "RtcConfiguration",
    "RtcIceServer",
    "MediaStream",
    "RtcDataChannelInit",
]

[dev-dependencies]
wasm-bindgen-test = "0.3.50"

[features]
default = [
    "websocket-client",
    "serial-client",
    "webrtc",
    "repl",
    "lsp",              # Make optional
]
lsp = ["datex-core/lsp_wasm"]
repl = []

allow_unsigned_blocks = ["datex-core/allow_unsigned_blocks"]

websocket-client = [] # full support
serial-client = []    # only required for frontend js runtime
webrtc = ["uuid"]     # only required for frontend js runtime
